### ISSUE TITLE
TCG Ruled Cards

### ISSUE THREAD

**Issue by Zayelion** [SalvationDevelopment/Salvation-Scripts-TCG#9]
I need a list of TCG ruled cards currently in our repository.

**Comment by StormWulf** [comment]
TCG ruled cards that need to be made (will add more later). Would appreciate if @GuybrushThreepwoodSD @0mniMage @LordVyro @Laughing-Luna helped to verify each of these.
- [ ] `Amorphactor Pain, the Imagination Dracoverlord [98287529]` : In the TCG, the effect "Your opponent skips their next Main Phase 1." starts a Chain Link. In the OCG, it does not start a Chain Link.
- [ ] `Attack of the Cornered Rat [84389640]` : In the TCG, you can activate the effect during damage calculation. In the OCG, you cannot.
- [ ] `Attack the Moon! [83715234]` : In the TCG, the effect of "Attack the Moon!" can be activated during the Damage Step. In the OCG, it cannot.
- [ ] `Beast Soul Swap [35149085]` : In the TCG, returning the targeted monster to the hand and Special Summoning 1 Beast-Type monster from your hand are considered to happen simultaneously. In the OCG, they are not considered to happen simultaneously.
- [ ] `Calming Magic [51773900]` : The OCG text specifies that you also cannot Set monsters, but not in the TCG
- [ ] `Card of Sanctity [42664989]` : In the TCG, you must have at least 1 card in both your hand and your side of the field to activate "Card of Sanctity". In the OCG, you only need 1 card in either your hand or your side of the field to activate it.
- [ ] `Chain Material [39980304]` : In the OCG, "Chain Material's" effect can be used with "Future Fusion". In the TCG, it cannot.
- [ ] `Dimensional Fissure [81674782]` : The ruling on "Gravekeeper's Servant" + "Dimensional Fissure" vs "Convulsion of Nature" has not been applied to the TCG yet. Until further notice, your opponent cannot attack, regardless of "Convulsion of Nature".
- [ ] `Dinomist Rex [63251695]` : In the TCG, if "Dinomist Rex" makes a second attack, it cannot attack again in a row using its own effect. In the OCG, it can attack again in a row using its own effect.
- [ ] `Doomcaliber Knight [78700060]` : In the TCG, if "Doomcaliber Knight" battles and is Tributed during damage calculation by its own effect, damage calculation will still be performed.
  In the OCG, it will not be performed.
- [ ] `Dragonecro Nethersoul Dragon [8198620]` : In the TCG, the effect of "Dragonecro Nethersoul Dragon" will not be activated if it battles a monster that does not have an original Level.
  In the OCG, it will be activated, but no "Dark Soul Token" will be Special Summoned.
- [ ] `Dragunity Knight - Gae Bulg [900787]` : In the TCG, you can activate the effect during damage calculation. In the OCG, you cannot.
- [ ] `Fortune Lady Light [34471458]` : In the TCG, the effect of "Fortune Lady Light" will activate even if it leaves the field while face-down. In the OCG, it will not.
- [ ] `Heat Wave [45141013]` : In the TCG, Gemini monsters that are treated as Normal Monsters on the field cannot be Normal Summoned while the effect of "Heat Wave" is applying. In the OCG, you can.
- [ ] `Majestic Star Dragon [7841112]` : In the OCG, "Majestic Star Dragon" cannot negate the effect of a Gemini monster being treated as a Normal Monster. It can in the TCG.
- [ ] `Symbol of Friendship [2295831]` : In the TCG, you can reveal this card if you draw it for your normal draw while you control no monsters. In the OCG, you can only reveal it if you control no cards.
- [ ] `The Phantom Knights of Dark Gauntlets [24212820]` : In the TCG, the effect to Special Summon itself from the Graveyard is mandatory. In the OCG, it is optional.

**Comment by Zayelion** [comment]
Minutes from meeting with YGOrg :
"Hallowed Barrier protects monsters in OCG"
